name: Check Python Code

on:
  push:
    branches:
      - main

jobs:
  check-python-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install requests

    - name: Add execute permissions
      run: chmod 777 app.py

    - name: Python Syntax Checker
  # You may pin to the exact commit or the version.
  # uses: cclauss/Find-Python-syntax-errors-action@90f67be9fb626b675a3971b1d08ab29851cb721f
    uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
